book:
  google-analytics: "G-E83F2C14MP"
  cookie-consent: true
  chapters:
    - index.qmd
    - part: "Introduction"      
      chapters:
        - 01-Introduction.ipynb
        - 02-Data-Summaries.ipynb
    - part: "Probability"
      chapters:          
        - 03-Probability.ipynb        
        - 04-Conditional-Probability.ipynb
        # - 04-Conditional-Probability-1-Class.ipynb
        # - 00-Garden-of-Forking-Data.qmd
        - 05-Counting-Things-Class.ipynb
        # - 04A-Simulation-Exercises.ipynb
        # - 05-Conditional-Probability.ipynb
    - part: "Random Variables and Distributions"
      chapters:
        - 06-Discrete-Random-Variables.ipynb
        - 07-Moments-Discrete-Distributions.ipynb
        - 08-Bi-variate-Discrete-Distributions.ipynb
        # - 09-Properties-Expectation-Variance.ipynb
        # - 10-Important-Discrete-Distributions.ipynb
        # - 11-Continuous-Distributions.ipynb
        # - 12-Estimation.ipynb
        # - 13-Sample-Exam.ipynb
        # - 14-Testing.ipynb
        # - 06-Random-Variables.ipynb
        # - 07-Distribution-Functions.ipynb
        # - 08-Moments.ipynb
        # - 03-Probability.ipynb
        # - 04-Combinatorics.ipynb
    # - 01-Introduction.ipynb
    # - 02-Descriptive-Statistics.ipynb
    # - 03-Probability.ipynb
    # - 04-Combinatorics.ipynb 
#    - 02-Garden-of-Forking-Data.qmd
    - references.qmd
